# Generated by Django 5.2.4 on 2025-08-08 15:14

import app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='doctor',
            managers=[
                ('objects', app.models.DoctorManager()),
            ],
        ),
    ]
