# Generated by Django 5.2.4 on 2025-08-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_doctor_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
