# Generated by Django 5.2.4 on 2025-07-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_patient_medicine_examination_problem_report_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='dose_per_day',
        ),
        migrations.AddField(
            model_name='medicine',
            name='frequency',
            field=models.CharField(default='1+1+1', max_length=50),
        ),
        migrations.AddField(
            model_name='medicine',
            name='remark',
            field=models.CharField(default='After Eat', max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='strength',
            field=models.CharField(default='500mg', max_length=50),
        ),
    ]
