# Generated by Django 5.2.4 on 2025-07-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_medicine_dose_per_day_medicine_frequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('uses_raw', models.TextField()),
                ('keywords', models.TextField()),
            ],
        ),
    ]
