# Generated by Django 6.0.7 on 2026-07-10 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_report_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalResearchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_level', models.CharField(blank=True, choices=[('', 'Select'), ('Illiterate', 'Illiterate'), ('Primary', 'Primary'), ('Secondary', 'Secondary'), ('Higher Secondary', 'Higher Secondary'), ('Graduate', 'Graduate'), ('Postgraduate', 'Postgraduate'), ('Other', 'Other')], max_length=30)),
                ('monthly_income', models.CharField(blank=True, help_text='Monthly income', max_length=50)),
                ('employment_status', models.CharField(blank=True, choices=[('', 'Select'), ('Employed', 'Employed'), ('Self-Employed', 'Self-Employed'), ('Unemployed', 'Unemployed'), ('Retired', 'Retired'), ('Student', 'Student'), ('Homemaker', 'Homemaker'), ('Other', 'Other')], max_length=30)),
                ('diagnosis', models.CharField(blank=True, help_text='Primary renal disease/cause of failure (e.g. ERA-PRD coding)', max_length=255)),
                ('comorbid_diabetes', models.BooleanField(default=False)),
                ('comorbid_hypertension', models.BooleanField(default=False)),
                ('comorbid_heart_failure', models.BooleanField(default=False)),
                ('comorbid_ischemic_heart_disease', models.BooleanField(default=False)),
                ('comorbid_peripheral_artery_disease', models.BooleanField(default=False)),
                ('comorbid_stroke', models.BooleanField(default=False)),
                ('smoking_status', models.CharField(blank=True, choices=[('', 'Select'), ('Never', 'Never'), ('Former', 'Former'), ('Current', 'Current')], max_length=20)),
                ('bmi', models.CharField(blank=True, max_length=20)),
                ('weight', models.CharField(blank=True, help_text='Weight (kg)', max_length=20)),
                ('height', models.CharField(blank=True, help_text='Height (cm)', max_length=20)),
                ('serum_creatinine', models.CharField(blank=True, max_length=20)),
                ('cystatin_c', models.CharField(blank=True, max_length=20)),
                ('egfr', models.CharField(blank=True, max_length=20, verbose_name='eGFR')),
                ('uacr', models.CharField(blank=True, max_length=20, verbose_name='uACR')),
                ('protein_levels', models.CharField(blank=True, max_length=20)),
                ('hemoglobin', models.CharField(blank=True, max_length=20)),
                ('ferritin', models.CharField(blank=True, max_length=20)),
                ('calcium', models.CharField(blank=True, max_length=20)),
                ('phosphorus', models.CharField(blank=True, max_length=20)),
                ('pth', models.CharField(blank=True, max_length=20, verbose_name='PTH')),
                ('potassium', models.CharField(blank=True, max_length=20)),
                ('bicarbonate', models.CharField(blank=True, max_length=20)),
                ('serum_albumin', models.CharField(blank=True, max_length=20)),
                ('crp', models.CharField(blank=True, max_length=20, verbose_name='CRP')),
                ('total_cholesterol', models.CharField(blank=True, max_length=20)),
                ('hba1c', models.CharField(blank=True, max_length=20, verbose_name='HbA1c')),
                ('krt_modality', models.CharField(blank=True, choices=[('', 'Select'), ('None', 'None / Pre-dialysis'), ('Hemodialysis', 'Hemodialysis (HD)'), ('Peritoneal Dialysis', 'Peritoneal Dialysis (PD)'), ('Transplantation', 'Transplantation')], max_length=30)),
                ('krt_initiation_date', models.DateField(blank=True, null=True)),
                ('modality_change_dates', models.CharField(blank=True, help_text='Dates of modality changes', max_length=255)),
                ('transplant_date', models.DateField(blank=True, null=True)),
                ('dialysis_duration', models.CharField(blank=True, help_text='e.g. 4 hours/session', max_length=50)),
                ('dialysis_frequency', models.CharField(blank=True, help_text='e.g. 3x/week', max_length=50)),
                ('vascular_access_type', models.CharField(blank=True, choices=[('', 'Select'), ('Fistula', 'Fistula'), ('Graft', 'Graft'), ('Catheter', 'Catheter'), ('N/A', 'N/A')], max_length=20)),
                ('med_esa', models.BooleanField(default=False, verbose_name='ESA (Erythropoietin-stimulating agents)')),
                ('med_iron', models.BooleanField(default=False, verbose_name='Iron')),
                ('med_phosphate_binders', models.BooleanField(default=False, verbose_name='Phosphate binders')),
                ('med_vitamin_d', models.BooleanField(default=False, verbose_name='Vitamin D')),
                ('med_calcimimetics', models.BooleanField(default=False, verbose_name='Calcimimetics')),
                ('med_ace_arb', models.BooleanField(default=False, verbose_name='Antihypertensives (ACE inhibitors/ARBs)')),
                ('med_diuretics', models.BooleanField(default=False, verbose_name='Diuretics')),
                ('med_statins', models.BooleanField(default=False, verbose_name='Statins')),
                ('med_immunosuppressives', models.BooleanField(default=False, verbose_name='Immunosuppressives')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_data', to='app.prescription')),
            ],
        ),
    ]
